server {
    listen 80;
    listen [::]:80;
    server_name 
        sand.DOMAIN_REPLACE_ME
        pad.DOMAIN_REPLACE_ME
        web.DOMAIN_REPLACE_ME
        api.DOMAIN_REPLACE_ME
        oauth.DOMAIN_REPLACE_ME
        sso.DOMAIN_REPLACE_ME;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name 
        sand.DOMAIN_REPLACE_ME
        pad.DOMAIN_REPLACE_ME
        web.DOMAIN_REPLACE_ME
        api.DOMAIN_REPLACE_ME
        oauth.DOMAIN_REPLACE_ME
        sso.DOMAIN_REPLACE_ME;

# certbot certonly --webroot \
#   -w /var/www/html \
#   -d sand.DOMAIN_REPLACE_ME \
#   -d pad.DOMAIN_REPLACE_ME \
#   -d web.DOMAIN_REPLACE_ME \
#   -d api.DOMAIN_REPLACE_ME \
#   -d oauth.DOMAIN_REPLACE_ME \
#   -d sso.DOMAIN_REPLACE_ME

    ssl_certificate /etc/letsencrypt/live/sand.DOMAIN_REPLACE_ME/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sand.DOMAIN_REPLACE_ME/privkey.pem;

    # openssl dhparam -out /etc/nginx/dhparam.pem 4096
    ssl_dhparam /etc/nginx/dhparam.pem;

    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;
    ssl_session_tickets off;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;

    client_max_body_size 150m;

    location / {
        proxy_pass http://127.0.0.1:8090;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }

    error_log /var/log/nginx/aurion_error.log;
    access_log /var/log/nginx/aurion_access.log;
}