SSLCipherSuite ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
SSLProxyCipherSuite ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
SSLHonorCipherOrder off
SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1
SSLProxyProtocol all -SSLv3 -TLSv1 -TLSv1.1
SSLSessionCache "shmcb:${APACHE_RUN_DIR}/ssl_scache(512000)"
SSLSessionCacheTimeout 86400
SSLSessionTickets off
SSLUseStapling on
SSLStaplingCache "shmcb:${APACHE_RUN_DIR}/ssl_stapling(32768)"

<VirtualHost *:443>
  ServerName pad.DOMAIN
  ServerAlias sand.DOMAIN
  Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains"


 SSLEngine on
  SSLCertificateFile /etc/letsencrypt/live/DOMAIN/cert.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/DOMAIN/privkey.pem
   
  BrowserMatch "MSIE [2-5]" \
        nokeepalive ssl-unclean-shutdown \
        downgrade-1.0 force-response-1.0
   
  Protocols h2 http/1.1
  AddType application/javascript mjs

  # =============================================================
  # AURION PROXY RULES
  # =============================================================
  RewriteEngine On

  RewriteCond %{REQUEST_URI} ^/login$
  RewriteCond %{QUERY_STRING} !(^|&)from=aurion(&|$) [NC]
  RewriteRule ^ https://web.DOMAIN [R=302,L]

  ProxyPass "/bridge-minimal.html" !
  ProxyPass "/bridge-sand.html" !

  ProxyPass "/cryptpad_websocket" "http://localhost:3013/" upgrade=websocket
  ProxyPassReverse "/cryptpad_websocket" "http://localhost:3013/"

  ProxyPass "/" "http://localhost:3010/" upgrade=websocket
  ProxyPassReverse "/" "http://localhost:3010/"

  Alias "/bridge-minimal.html" "/home/aurion/aurionmail/bridges/cryptpad_main_bridge.html"

  <Location "/bridge-minimal.html">
     Header always set Content-Security-Policy "frame-ancestors https://web.DOMAIN https://sso.DOMAIN"
     Require all granted
  </Location>

 Alias "/bridge-sand.html" "/home/aurion/aurionmail/bridges/cryptpad_sandbox_bridge.html"

  <Location "/bridge-sand.html">
     Header always set Content-Security-Policy "frame-ancestors https://pad.DOMAIN https://web.DOMAIN https://sso.DOMAIN"
     Require all granted
  </Location>

  LimitRequestBody 157286400

</VirtualHost>